FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY catalog_service.py .
COPY database.py .
COPY books.csv .

EXPOSE 5001

CMD ["python", "catalog_service.py"]