FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY order_service.py .
COPY database.py .
COPY orders.csv .

EXPOSE 5002

CMD ["python", "order_service.py"]